apiVersion: v1
kind: Service
metadata:
  name: log-ingestion-service
  namespace: threat-detection
spec:
  selector:
    app: log-ingestion
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer